module.exports = Object.freeze({
    MODAL_BODY_TYPES: {
        USER_DETAIL: "USER_DETAIL",
        ADD_NEW_TEAM_MEMBER: "ADD_NEW_TEAM_MEMBER",
        CONFIRMATION: "CONFIRMATION",
        DEFAULT: "",
    },

    RIGHT_DRAWER_TYPES: {
        NOTIFICATION: "NOTIFICATION",
        CALENDAR_EVENTS: "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES: {
        DELETE_TEAM_MEMBER: "DELETE_TEAM_MEMBER",
    },
});
